---
name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.9'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.5.1'
      - name: Run Tests
        run: |
          poetry install
          poetry run isort --check .
          poetry run flake8 .
